//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAndLoadTestProject3
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;


    public class PPOnlineMeikartaCoded : WebTest
    {

        public PPOnlineMeikartaCoded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("http://pponline.meikarta.com/pponline/");
            request1.ThinkTime = 1;
            WebTestRequest request1Dependent1 = new WebTestRequest("https://fonts.googleapis.com/css");
            request1Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/"));
            request1Dependent1.QueryStringParameters.Add("family", "Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic", false, false);
            request1.DependentRequests.Add(request1Dependent1);
            WebTestRequest request1Dependent2 = new WebTestRequest("https://fonts.gstatic.com/s/sourcesanspro/v10/toadOcfmlt9b38dHJxOBGNbE_oMaV8t2eFe" +
                    "ISPpzbdE.woff");
            request1Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/"));
            request1.DependentRequests.Add(request1Dependent2);
            WebTestRequest request1Dependent3 = new WebTestRequest("https://fonts.gstatic.com/s/sourcesanspro/v10/ODelI1aHBYDBqgeIAH2zlBM0YzuT7MdOe03" +
                    "otPbuUS0.woff");
            request1Dependent3.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/"));
            request1.DependentRequests.Add(request1Dependent3);
            WebTestRequest request1Dependent4 = new WebTestRequest("https://fonts.gstatic.com/s/sourcesanspro/v10/toadOcfmlt9b38dHJxOBGJ6-ys_j0H4QL65" +
                    "VLqzI3wI.woff");
            request1Dependent4.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/"));
            request1.DependentRequests.Add(request1Dependent4);
            WebTestRequest request1Dependent5 = new WebTestRequest("https://fonts.gstatic.com/s/sourcesanspro/v10/toadOcfmlt9b38dHJxOBGFkQc6VGVFSmCnC" +
                    "_l7QZG60.woff");
            request1Dependent5.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/"));
            request1.DependentRequests.Add(request1Dependent5);
            WebTestRequest request1Dependent6 = new WebTestRequest("https://fonts.gstatic.com/s/sourcesanspro/v10/fpTVHK8qsXbIeTHTrnQH6GGomRtBD2u8FwS" +
                    "Y4jjlmeA.woff");
            request1Dependent6.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/"));
            request1.DependentRequests.Add(request1Dependent6);
            WebTestRequest request1Dependent7 = new WebTestRequest("https://fonts.gstatic.com/s/sourcesanspro/v10/M2Jd71oPJhLKp0zdtTvoMzNrcjQuD0pTu1z" +
                    "a2FULaMs.woff");
            request1Dependent7.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/"));
            request1.DependentRequests.Add(request1Dependent7);
            WebTestRequest request1Dependent8 = new WebTestRequest("https://fonts.gstatic.com/s/sourcesanspro/v10/fpTVHK8qsXbIeTHTrnQH6PULlOK_XQENnt2" +
                    "ryrY843E.woff");
            request1Dependent8.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/"));
            request1.DependentRequests.Add(request1Dependent8);
            WebTestRequest request1Dependent9 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/fonts/glyphicons-halflings-regular.eot" +
                    "");
            request1Dependent9.ThinkTime = 722;
            request1Dependent9.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/"));
            request1Dependent9.QueryStringParameters.Add("", "", false, false);
            request1.DependentRequests.Add(request1Dependent9);
            ExtractHiddenFields extractionRule1 = new ExtractHiddenFields();
            extractionRule1.Required = true;
            extractionRule1.HtmlDecode = true;
            extractionRule1.ContextParameterName = "1";
            request1.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule1.Extract);
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("http://pponline.meikarta.com/pponline/");
            request2.Method = "POST";
            request2.ExpectedResponseUrl = "http://pponline.meikarta.com/pponline/wf/index.aspx";
            request2.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/"));
            FormPostHttpBody request2Body = new FormPostHttpBody();
            request2Body.FormPostParameters.Add("SMMain_HiddenField", this.Context["$HIDDEN1.SMMain_HiddenField"].ToString());
            request2Body.FormPostParameters.Add("__EVENTTARGET", this.Context["$HIDDEN1.__EVENTTARGET"].ToString());
            request2Body.FormPostParameters.Add("__EVENTARGUMENT", this.Context["$HIDDEN1.__EVENTARGUMENT"].ToString());
            request2Body.FormPostParameters.Add("__VIEWSTATE", this.Context["$HIDDEN1.__VIEWSTATE"].ToString());
            request2Body.FormPostParameters.Add("__VIEWSTATEGENERATOR", this.Context["$HIDDEN1.__VIEWSTATEGENERATOR"].ToString());
            request2Body.FormPostParameters.Add("_default", "1");
            request2Body.FormPostParameters.Add("txtEmail", "228865660010");
            request2Body.FormPostParameters.Add("txtPassword", "hello");
            request2.Body = request2Body;
            WebTestRequest request2Dependent1 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/fonts/fonts/fontawesome-webfont.eot");
            request2Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/index.aspx"));
            request2Dependent1.QueryStringParameters.Add("", "", false, false);
            request2.DependentRequests.Add(request2Dependent1);
            WebTestRequest request2Dependent2 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/font/fontawesome-webfont.eot");
            request2Dependent2.ThinkTime = 1;
            request2Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/index.aspx"));
            request2Dependent2.QueryStringParameters.Add("", "", false, false);
            request2.DependentRequests.Add(request2Dependent2);
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/font/fontawesome-webfont.woff");
            request3.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/index.aspx"));
            request3.QueryStringParameters.Add("v", "3.0.2", false, false);
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/font/fontawesome-webfont.ttf");
            request4.ThinkTime = 4;
            request4.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/index.aspx"));
            request4.QueryStringParameters.Add("v", "3.0.2", false, false);
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("http://pponline.meikarta.com/pponline/wf/trOrder.aspx");
            request5.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/index.aspx"));
            WebTestRequest request5Dependent1 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/fonts/fonts/fontawesome-webfont.eot");
            request5Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrder.aspx"));
            request5Dependent1.QueryStringParameters.Add("", "", false, false);
            request5.DependentRequests.Add(request5Dependent1);
            WebTestRequest request5Dependent2 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/font/fontawesome-webfont.eot");
            request5Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrder.aspx"));
            request5Dependent2.QueryStringParameters.Add("", "", false, false);
            request5.DependentRequests.Add(request5Dependent2);
            ExtractHiddenFields extractionRule2 = new ExtractHiddenFields();
            extractionRule2.Required = true;
            extractionRule2.HtmlDecode = true;
            extractionRule2.ContextParameterName = "1";
            request5.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule2.Extract);
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/font/fontawesome-webfont.woff");
            request6.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrder.aspx"));
            request6.QueryStringParameters.Add("v", "3.0.2", false, false);
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/font/fontawesome-webfont.ttf");
            request7.ThinkTime = 2;
            request7.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrder.aspx"));
            request7.QueryStringParameters.Add("v", "3.0.2", false, false);
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest("http://pponline.meikarta.com/pponline/wf/trOrder.aspx");
            request8.Method = "POST";
            request8.ExpectedResponseUrl = "http://pponline.meikarta.com/pponline/wf/trOrder.aspx?p=1&x=YmRmPSZ0eHRLZXl3b3JkP" +
                "SZ1bj0mYmR0PSZyZWZyZXNoPTE=";
            request8.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrder.aspx"));
            FormPostHttpBody request8Body = new FormPostHttpBody();
            request8Body.FormPostParameters.Add("SMMain_HiddenField", this.Context["$HIDDEN1.SMMain_HiddenField"].ToString());
            request8Body.FormPostParameters.Add("__EVENTTARGET", this.Context["$HIDDEN1.__EVENTTARGET"].ToString());
            request8Body.FormPostParameters.Add("__EVENTARGUMENT", this.Context["$HIDDEN1.__EVENTARGUMENT"].ToString());
            request8Body.FormPostParameters.Add("__VIEWSTATE", this.Context["$HIDDEN1.__VIEWSTATE"].ToString());
            request8Body.FormPostParameters.Add("__VIEWSTATEGENERATOR", this.Context["$HIDDEN1.__VIEWSTATEGENERATOR"].ToString());
            request8Body.FormPostParameters.Add("__EVENTVALIDATION", this.Context["$HIDDEN1.__EVENTVALIDATION"].ToString());
            request8Body.FormPostParameters.Add("_mProject", this.Context["$HIDDEN1._mProject"].ToString());
            request8Body.FormPostParameters.Add("_mProjectInput", this.Context["$HIDDEN1._mProjectInput"].ToString());
            request8Body.FormPostParameters.Add("_mUser", "1");
            request8Body.FormPostParameters.Add("_psCode", this.Context["$HIDDEN1._psCode"].ToString());
            request8Body.FormPostParameters.Add("txtUname", "");
            request8Body.FormPostParameters.Add("txtKeyword", "");
            request8.Body = request8Body;
            WebTestRequest request8Dependent1 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/fonts/fonts/fontawesome-webfont.eot");
            request8Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrder.aspx?p=1&x=YmRmPSZ0eHRLZXl3b3JkP" +
                        "SZ1bj0mYmR0PSZyZWZyZXNoPTE="));
            request8Dependent1.QueryStringParameters.Add("", "", false, false);
            request8.DependentRequests.Add(request8Dependent1);
            WebTestRequest request8Dependent2 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/font/fontawesome-webfont.eot");
            request8Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrder.aspx?p=1&x=YmRmPSZ0eHRLZXl3b3JkP" +
                        "SZ1bj0mYmR0PSZyZWZyZXNoPTE="));
            request8Dependent2.QueryStringParameters.Add("", "", false, false);
            request8.DependentRequests.Add(request8Dependent2);
            ExtractHiddenFields extractionRule3 = new ExtractHiddenFields();
            extractionRule3.Required = true;
            extractionRule3.HtmlDecode = true;
            extractionRule3.ContextParameterName = "1";
            request8.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule3.Extract);
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/font/fontawesome-webfont.woff");
            request9.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrder.aspx?p=1&x=YmRmPSZ0eHRLZXl3b3JkP" +
                        "SZ1bj0mYmR0PSZyZWZyZXNoPTE="));
            request9.QueryStringParameters.Add("v", "3.0.2", false, false);
            yield return request9;
            request9 = null;

            WebTestRequest request10 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/font/fontawesome-webfont.ttf");
            request10.ThinkTime = 2;
            request10.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrder.aspx?p=1&x=YmRmPSZ0eHRLZXl3b3JkP" +
                        "SZ1bj0mYmR0PSZyZWZyZXNoPTE="));
            request10.QueryStringParameters.Add("v", "3.0.2", false, false);
            yield return request10;
            request10 = null;

            WebTestRequest request11 = new WebTestRequest("http://pponline.meikarta.com/pponline/wf/trOrder.aspx");
            request11.Method = "POST";
            request11.ExpectedResponseUrl = "http://pponline.meikarta.com/pponline/wf/trOrder.aspx?pc=00000000&p=1&r=0&x=cmVmc" +
                "mVzaD0xJmtleXdvcmQ9";
            request11.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrder.aspx?p=1&x=YmRmPSZ0eHRLZXl3b3JkP" +
                        "SZ1bj0mYmR0PSZyZWZyZXNoPTE="));
            request11.QueryStringParameters.Add("p", "1", false, false);
            request11.QueryStringParameters.Add("x", "YmRmPSZ0eHRLZXl3b3JkPSZ1bj0mYmR0PSZyZWZyZXNoPTE%3d", false, false);
            FormPostHttpBody request11Body = new FormPostHttpBody();
            request11Body.FormPostParameters.Add("SMMain_HiddenField", this.Context["$HIDDEN1.SMMain_HiddenField"].ToString());
            request11Body.FormPostParameters.Add("__EVENTTARGET", this.Context["$HIDDEN1.__EVENTTARGET"].ToString());
            request11Body.FormPostParameters.Add("__EVENTARGUMENT", this.Context["$HIDDEN1.__EVENTARGUMENT"].ToString());
            request11Body.FormPostParameters.Add("__VIEWSTATE", this.Context["$HIDDEN1.__VIEWSTATE"].ToString());
            request11Body.FormPostParameters.Add("__VIEWSTATEGENERATOR", this.Context["$HIDDEN1.__VIEWSTATEGENERATOR"].ToString());
            request11Body.FormPostParameters.Add("__EVENTVALIDATION", this.Context["$HIDDEN1.__EVENTVALIDATION"].ToString());
            request11Body.FormPostParameters.Add("_mProject", "0");
            request11Body.FormPostParameters.Add("_mProjectInput", this.Context["$HIDDEN1._mProjectInput"].ToString());
            request11Body.FormPostParameters.Add("_mUser", this.Context["$HIDDEN1._mUser"].ToString());
            request11Body.FormPostParameters.Add("_psCode", "00000000");
            request11Body.FormPostParameters.Add("txtUname", "");
            request11Body.FormPostParameters.Add("txtKeyword", "");
            request11.Body = request11Body;
            WebTestRequest request11Dependent1 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/fonts/fonts/fontawesome-webfont.eot");
            request11Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrder.aspx?pc=00000000&p=1&r=0&x=cmVmc" +
                        "mVzaD0xJmtleXdvcmQ9"));
            request11Dependent1.QueryStringParameters.Add("", "", false, false);
            request11.DependentRequests.Add(request11Dependent1);
            WebTestRequest request11Dependent2 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/font/fontawesome-webfont.eot");
            request11Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrder.aspx?pc=00000000&p=1&r=0&x=cmVmc" +
                        "mVzaD0xJmtleXdvcmQ9"));
            request11Dependent2.QueryStringParameters.Add("", "", false, false);
            request11.DependentRequests.Add(request11Dependent2);
            WebTestRequest request11Dependent3 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/font/fontawesome-webfont.woff");
            request11Dependent3.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrder.aspx?pc=00000000&p=1&r=0&x=cmVmc" +
                        "mVzaD0xJmtleXdvcmQ9"));
            request11Dependent3.QueryStringParameters.Add("v", "3.0.2", false, false);
            request11.DependentRequests.Add(request11Dependent3);
            WebTestRequest request11Dependent4 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/font/fontawesome-webfont.ttf");
            request11Dependent4.ThinkTime = 3;
            request11Dependent4.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrder.aspx?pc=00000000&p=1&r=0&x=cmVmc" +
                        "mVzaD0xJmtleXdvcmQ9"));
            request11Dependent4.QueryStringParameters.Add("v", "3.0.2", false, false);
            request11.DependentRequests.Add(request11Dependent4);
            ExtractHiddenFields extractionRule4 = new ExtractHiddenFields();
            extractionRule4.Required = true;
            extractionRule4.HtmlDecode = true;
            extractionRule4.ContextParameterName = "1";
            request11.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule4.Extract);
            yield return request11;
            request11 = null;

            WebTestRequest request12 = new WebTestRequest("http://pponline.meikarta.com/pponline/wf/trOrder.aspx");
            request12.Method = "POST";
            request12.ExpectedResponseUrl = "http://pponline.meikarta.com/pponline/wf/trOrderInput.aspx?pc=00000000&r=0&p=4";
            request12.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrder.aspx?pc=00000000&p=1&r=0&x=cmVmc" +
                        "mVzaD0xJmtleXdvcmQ9"));
            request12.QueryStringParameters.Add("pc", "00000000", false, false);
            request12.QueryStringParameters.Add("p", "1", false, false);
            request12.QueryStringParameters.Add("r", "0", false, false);
            request12.QueryStringParameters.Add("x", "cmVmcmVzaD0xJmtleXdvcmQ9", false, false);
            FormPostHttpBody request12Body = new FormPostHttpBody();
            request12Body.FormPostParameters.Add("SMMain_HiddenField", this.Context["$HIDDEN1.SMMain_HiddenField"].ToString());
            request12Body.FormPostParameters.Add("__EVENTTARGET", this.Context["$HIDDEN1.__EVENTTARGET"].ToString());
            request12Body.FormPostParameters.Add("__EVENTARGUMENT", this.Context["$HIDDEN1.__EVENTARGUMENT"].ToString());
            request12Body.FormPostParameters.Add("__VIEWSTATE", this.Context["$HIDDEN1.__VIEWSTATE"].ToString());
            request12Body.FormPostParameters.Add("__VIEWSTATEGENERATOR", this.Context["$HIDDEN1.__VIEWSTATEGENERATOR"].ToString());
            request12Body.FormPostParameters.Add("__EVENTVALIDATION", this.Context["$HIDDEN1.__EVENTVALIDATION"].ToString());
            request12Body.FormPostParameters.Add("_mProject", this.Context["$HIDDEN1._mProject"].ToString());
            request12Body.FormPostParameters.Add("_mProjectInput", "4");
            request12Body.FormPostParameters.Add("_mUser", this.Context["$HIDDEN1._mUser"].ToString());
            request12Body.FormPostParameters.Add("_psCode", this.Context["$HIDDEN1._psCode"].ToString());
            request12Body.FormPostParameters.Add("txtUname", "");
            request12Body.FormPostParameters.Add("txtKeyword", "");
            request12.Body = request12Body;
            WebTestRequest request12Dependent1 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/fonts/fonts/fontawesome-webfont.eot");
            request12Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrderInput.aspx?pc=00000000&r=0&p=4"));
            request12Dependent1.QueryStringParameters.Add("", "", false, false);
            request12.DependentRequests.Add(request12Dependent1);
            WebTestRequest request12Dependent2 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/font/fontawesome-webfont.eot");
            request12Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrderInput.aspx?pc=00000000&r=0&p=4"));
            request12Dependent2.QueryStringParameters.Add("", "", false, false);
            request12.DependentRequests.Add(request12Dependent2);
            WebTestRequest request12Dependent3 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/font/fontawesome-webfont.woff");
            request12Dependent3.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrderInput.aspx?pc=00000000&r=0&p=4"));
            request12Dependent3.QueryStringParameters.Add("v", "3.0.2", false, false);
            request12.DependentRequests.Add(request12Dependent3);
            WebTestRequest request12Dependent4 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/font/fontawesome-webfont.ttf");
            request12Dependent4.ThinkTime = 20;
            request12Dependent4.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrderInput.aspx?pc=00000000&r=0&p=4"));
            request12Dependent4.QueryStringParameters.Add("v", "3.0.2", false, false);
            request12.DependentRequests.Add(request12Dependent4);
            ExtractHiddenFields extractionRule5 = new ExtractHiddenFields();
            extractionRule5.Required = true;
            extractionRule5.HtmlDecode = true;
            extractionRule5.ContextParameterName = "1";
            request12.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule5.Extract);
            yield return request12;
            request12 = null;

            WebTestRequest request13 = new WebTestRequest("http://pponline.meikarta.com/pponline/wf/trOrderInput.aspx");
            request13.Method = "POST";
            request13.ExpectedResponseUrl = "http://pponline.meikarta.com/pponline/wf/trOrderInput.aspx?pc=00000000&rr=11594&p" +
                "=4&r=0&x=bm90ZT1UaGFuayt5b3UhK1lvdXIrb3JkZXIraXMrY29tcGxldGUuK1BsZWFzZStwYXkrbm9" +
                "3K29yK3lvdStjYW4rcGF5K2xhdGVyK2Zyb20rQkYrT3JkZXIrSGlzdG9yeSttZW51Lg==";
            request13.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrderInput.aspx?pc=00000000&r=0&p=4"));
            request13.QueryStringParameters.Add("pc", "00000000", false, false);
            request13.QueryStringParameters.Add("r", "0", false, false);
            request13.QueryStringParameters.Add("p", "4", false, false);
            FormPostHttpBody request13Body = new FormPostHttpBody();
            request13Body.FormPostParameters.Add("SMMain_HiddenField", this.Context["$HIDDEN1.SMMain_HiddenField"].ToString());
            request13Body.FormPostParameters.Add("__EVENTTARGET", this.Context["$HIDDEN1.__EVENTTARGET"].ToString());
            request13Body.FormPostParameters.Add("__EVENTARGUMENT", this.Context["$HIDDEN1.__EVENTARGUMENT"].ToString());
            request13Body.FormPostParameters.Add("__VIEWSTATE", this.Context["$HIDDEN1.__VIEWSTATE"].ToString());
            request13Body.FormPostParameters.Add("__VIEWSTATEGENERATOR", this.Context["$HIDDEN1.__VIEWSTATEGENERATOR"].ToString());
            request13Body.FormPostParameters.Add("__EVENTVALIDATION", this.Context["$HIDDEN1.__EVENTVALIDATION"].ToString());
            request13Body.FormPostParameters.Add("_saveOrder", "1");
            request13Body.FormPostParameters.Add("_insertNew", this.Context["$HIDDEN1._insertNew"].ToString());
            request13Body.FormPostParameters.Add("_orderRef", this.Context["$HIDDEN1._orderRef"].ToString());
            request13Body.FormPostParameters.Add("_orderCode", this.Context["$HIDDEN1._orderCode"].ToString());
            request13Body.FormPostParameters.Add("_totalAmt", this.Context["$HIDDEN1._totalAmt"].ToString());
            request13Body.FormPostParameters.Add("_qty", this.Context["$HIDDEN1._qty"].ToString());
            request13Body.FormPostParameters.Add("_cName", this.Context["$HIDDEN1._cName"].ToString());
            request13Body.FormPostParameters.Add("_email", this.Context["$HIDDEN1._email"].ToString());
            request13Body.FormPostParameters.Add("_userRef", this.Context["$HIDDEN1._userRef"].ToString());
            request13Body.FormPostParameters.Add("_reOrder", this.Context["$HIDDEN1._reOrder"].ToString());
            request13Body.FormPostParameters.Add("txtUserRef", this.Context["$HIDDEN1.txtUserRef"].ToString());
            request13Body.FormPostParameters.Add("txtClusterCode", this.Context["$HIDDEN1.txtClusterCode"].ToString());
            request13Body.FormPostParameters.Add("txtProjectCode", this.Context["$HIDDEN1.txtProjectCode"].ToString());
            request13Body.FormPostParameters.Add("txtProjectRef", this.Context["$HIDDEN1.txtProjectRef"].ToString());
            request13Body.FormPostParameters.Add("txtsearch", "");
            request13Body.FormPostParameters.Add("selPreferredType", "10");
            request13Body.FormPostParameters.Add("selTerm", "2");
            request13Body.FormPostParameters.Add("txtPassPrice", "10,000");
            request13Body.FormPostParameters.Add("txtQty", "1");
            request13Body.FormPostParameters.Add("txtTotalPrice", "10,000");
            request13Body.FormPostParameters.Add("txtNoted", "");
            request13Body.FormPostParameters.Add("_payMethod", this.Context["$HIDDEN1._payMethod"].ToString());
            request13.Body = request13Body;
            WebTestRequest request13Dependent1 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/fonts/fonts/fontawesome-webfont.eot");
            request13Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrderInput.aspx?pc=00000000&rr=11594&p" +
                        "=4&r=0&x=bm90ZT1UaGFuayt5b3UhK1lvdXIrb3JkZXIraXMrY29tcGxldGUuK1BsZWFzZStwYXkrbm9" +
                        "3K29yK3lvdStjYW4rcGF5K2xhdGVyK2Zyb20rQkYrT3JkZXIrSGlzdG9yeSttZW51Lg=="));
            request13Dependent1.QueryStringParameters.Add("", "", false, false);
            request13.DependentRequests.Add(request13Dependent1);
            WebTestRequest request13Dependent2 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/font/fontawesome-webfont.eot");
            request13Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrderInput.aspx?pc=00000000&rr=11594&p" +
                        "=4&r=0&x=bm90ZT1UaGFuayt5b3UhK1lvdXIrb3JkZXIraXMrY29tcGxldGUuK1BsZWFzZStwYXkrbm9" +
                        "3K29yK3lvdStjYW4rcGF5K2xhdGVyK2Zyb20rQkYrT3JkZXIrSGlzdG9yeSttZW51Lg=="));
            request13Dependent2.QueryStringParameters.Add("", "", false, false);
            request13.DependentRequests.Add(request13Dependent2);
            WebTestRequest request13Dependent3 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/font/fontawesome-webfont.woff");
            request13Dependent3.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrderInput.aspx?pc=00000000&rr=11594&p" +
                        "=4&r=0&x=bm90ZT1UaGFuayt5b3UhK1lvdXIrb3JkZXIraXMrY29tcGxldGUuK1BsZWFzZStwYXkrbm9" +
                        "3K29yK3lvdStjYW4rcGF5K2xhdGVyK2Zyb20rQkYrT3JkZXIrSGlzdG9yeSttZW51Lg=="));
            request13Dependent3.QueryStringParameters.Add("v", "3.0.2", false, false);
            request13.DependentRequests.Add(request13Dependent3);
            WebTestRequest request13Dependent4 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/font/fontawesome-webfont.ttf");
            request13Dependent4.ThinkTime = 15;
            request13Dependent4.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrderInput.aspx?pc=00000000&rr=11594&p" +
                        "=4&r=0&x=bm90ZT1UaGFuayt5b3UhK1lvdXIrb3JkZXIraXMrY29tcGxldGUuK1BsZWFzZStwYXkrbm9" +
                        "3K29yK3lvdStjYW4rcGF5K2xhdGVyK2Zyb20rQkYrT3JkZXIrSGlzdG9yeSttZW51Lg=="));
            request13Dependent4.QueryStringParameters.Add("v", "3.0.2", false, false);
            request13.DependentRequests.Add(request13Dependent4);
            yield return request13;
            request13 = null;

            WebTestRequest request14 = new WebTestRequest("http://pponline.meikarta.com/pponline/wf/logout.aspx");
            request14.ExpectedResponseUrl = "http://pponline.meikarta.com/pponline/Default.aspx";
            request14.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/wf/trOrderInput.aspx?pc=00000000&rr=11594&p" +
                        "=4&r=0&x=bm90ZT1UaGFuayt5b3UhK1lvdXIrb3JkZXIraXMrY29tcGxldGUuK1BsZWFzZStwYXkrbm9" +
                        "3K29yK3lvdStjYW4rcGF5K2xhdGVyK2Zyb20rQkYrT3JkZXIrSGlzdG9yeSttZW51Lg=="));
            WebTestRequest request14Dependent1 = new WebTestRequest("https://fonts.googleapis.com/css");
            request14Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/Default.aspx"));
            request14Dependent1.QueryStringParameters.Add("family", "Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic", false, false);
            request14.DependentRequests.Add(request14Dependent1);
            WebTestRequest request14Dependent2 = new WebTestRequest("https://fonts.gstatic.com/s/sourcesanspro/v10/toadOcfmlt9b38dHJxOBGNbE_oMaV8t2eFe" +
                    "ISPpzbdE.woff");
            request14Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/Default.aspx"));
            request14.DependentRequests.Add(request14Dependent2);
            WebTestRequest request14Dependent3 = new WebTestRequest("https://fonts.gstatic.com/s/sourcesanspro/v10/ODelI1aHBYDBqgeIAH2zlBM0YzuT7MdOe03" +
                    "otPbuUS0.woff");
            request14Dependent3.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/Default.aspx"));
            request14.DependentRequests.Add(request14Dependent3);
            WebTestRequest request14Dependent4 = new WebTestRequest("https://fonts.gstatic.com/s/sourcesanspro/v10/toadOcfmlt9b38dHJxOBGJ6-ys_j0H4QL65" +
                    "VLqzI3wI.woff");
            request14Dependent4.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/Default.aspx"));
            request14.DependentRequests.Add(request14Dependent4);
            WebTestRequest request14Dependent5 = new WebTestRequest("https://fonts.gstatic.com/s/sourcesanspro/v10/toadOcfmlt9b38dHJxOBGFkQc6VGVFSmCnC" +
                    "_l7QZG60.woff");
            request14Dependent5.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/Default.aspx"));
            request14.DependentRequests.Add(request14Dependent5);
            WebTestRequest request14Dependent6 = new WebTestRequest("https://fonts.gstatic.com/s/sourcesanspro/v10/fpTVHK8qsXbIeTHTrnQH6GGomRtBD2u8FwS" +
                    "Y4jjlmeA.woff");
            request14Dependent6.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/Default.aspx"));
            request14.DependentRequests.Add(request14Dependent6);
            WebTestRequest request14Dependent7 = new WebTestRequest("https://fonts.gstatic.com/s/sourcesanspro/v10/M2Jd71oPJhLKp0zdtTvoMzNrcjQuD0pTu1z" +
                    "a2FULaMs.woff");
            request14Dependent7.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/Default.aspx"));
            request14.DependentRequests.Add(request14Dependent7);
            WebTestRequest request14Dependent8 = new WebTestRequest("https://fonts.gstatic.com/s/sourcesanspro/v10/fpTVHK8qsXbIeTHTrnQH6PULlOK_XQENnt2" +
                    "ryrY843E.woff");
            request14Dependent8.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/Default.aspx"));
            request14.DependentRequests.Add(request14Dependent8);
            WebTestRequest request14Dependent9 = new WebTestRequest("http://pponline.meikarta.com/pponline/skin/fonts/glyphicons-halflings-regular.eot" +
                    "");
            request14Dependent9.Headers.Add(new WebTestRequestHeader("Referer", "http://pponline.meikarta.com/pponline/Default.aspx"));
            request14Dependent9.QueryStringParameters.Add("", "", false, false);
            request14.DependentRequests.Add(request14Dependent9);
            yield return request14;
            request14 = null;
        }
    }
}
